### ISSUE TITLE
Thee Debug Drawer Examples Down

### ISSUE THREAD

**Issue by niko-dellic** [isaac-mason/recast-navigation-js#429]
The storybook examples for Three Debug Drawer are all currently encountering an error:

`TypeError: r.resize is not a function
    at https://recast-navigation-js.isaacmason.com/assets/debug-drawer.stories-D9Q5HZkv.js:1:1275
    at Zl (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3879:20862)
    at So (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3879:40381)
    at rC (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3879:39146)
    at wo (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3879:38254)
    at fx (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3879:34889)
    at Ur (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3877:4689)
    at rC (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3879:39201)
    at wo (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3879:38254)
    at dx (https://recast-navigation-js.isaacmason.com/assets/parameters-DaYMCO2B.js:3879:33742)`

**Comment by isaac-mason** [comment]
Hi, thanks for raising this. This has been fixed in this commit: https://github.com/isaac-mason/recast-navigation-js/commit/d617943eb6e2beb7b02ce3b6c76cdbd2872c254a

Fixed storybook examples are deploying now 🙂
